#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Oct 07, 2019 06:02:32 PM CEST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_text_desc) $desc
set vTcl(actual_gui_font_text_name) [font create {*}$desc]
set desc "-family {DejaVu Sans Mono} -size 10"
set vTcl(actual_gui_font_fixed_desc) $desc
set vTcl(actual_gui_font_fixed_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_menu_desc) $desc
set vTcl(actual_gui_font_menu_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 10"
set vTcl(actual_gui_font_tooltip_desc) $desc
set vTcl(actual_gui_font_tooltip_name) [font create {*}$desc]
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1081x782+454+173
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Qaps"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TPanedwindow -background $vTcl(actual_gui_bg)
    ttk::style configure TPanedwindow.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TPanedwindow.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TPanedwindow.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::panedwindow $top.tPa43 \
        -orient horizontal 
    vTcl:DefineAlias "$top.tPa43" "TPanedwindow1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $top.tPa43.p1 \
        -relief flat -width 485 -height 760 
    vTcl:DefineAlias "$top.tPa43.p1" "TPanedwindow1_p1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $top.tPa43.p1
    button $site_4_0.but44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Open Qtractor Project} 
    vTcl:DefineAlias "$site_4_0.but44" "button_qopen" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but44 <ButtonRelease-1> {
        lambda e: xxx(e)
    }
    button $site_4_0.but46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {BACKUP Qtractor Project} 
    vTcl:DefineAlias "$site_4_0.but46" "button_qbackup" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.but46
    label $site_4_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -anchor n \
        -background #23ccd8 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text Label 
    vTcl:DefineAlias "$site_4_0.lab48" "label_qproject" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure Treeview.Heading -background $vTcl(pr,guicomplement_color)
    ttk::style configure Treeview.Heading -font "$vTcl(actual_gui_font_dft_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_0.scr44 \
        -background $vTcl(actual_gui_bg) -height 661 -highlightcolor black \
        -width 483 
    vTcl:DefineAlias "$site_4_0.scr44" "tree_ctrl_qtractor" vTcl:WidgetProc "Toplevel1" 1
        .top42.tPa43.p1.scr44.01 configure -columns {}
        .top42.tPa43.p1.scr44.01 heading #0 -text {Tree}
        .top42.tPa43.p1.scr44.01 heading #0 -anchor center
        .top42.tPa43.p1.scr44.01 column #0 -width 233
        .top42.tPa43.p1.scr44.01 column #0 -minwidth 20
        .top42.tPa43.p1.scr44.01 column #0 -stretch 1
        .top42.tPa43.p1.scr44.01 column #0 -anchor w
    button $site_4_0.but47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Save Qtractor Project} 
    vTcl:DefineAlias "$site_4_0.but47" "button_qsave" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.but44 \
        -in $site_4_0 -x 5 -y 10 -width 191 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but46 \
        -in $site_4_0 -x 195 -y 10 -width 191 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab48 \
        -in $site_4_0 -x 5 -y 40 -width 475 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.scr44 \
        -in $site_4_0 -x 0 -y 60 -width 483 -relwidth 0 -height 661 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but47 \
        -in $site_4_0 -x 2 -y 728 -width 191 -height 31 -anchor nw \
        -bordermode ignore 
    $top.tPa43 add $top.tPa43.p1 
        
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $top.tPa43.p3 \
        -borderwidth 1 -relief flat -width 80 
    vTcl:DefineAlias "$top.tPa43.p3" "TPanedwindow1_pb" vTcl:WidgetProc "Toplevel1" 1
    set site_4_1 $top.tPa43.p3
    label $site_4_1.lab43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Plugin 
    vTcl:DefineAlias "$site_4_1.lab43" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_1.but44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text > 
    vTcl:DefineAlias "$site_4_1.but44" "button_q_to_a" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_1.but43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text < 
    vTcl:DefineAlias "$site_4_1.but43" "button_a_to_q" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_1.lab44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Track 
    vTcl:DefineAlias "$site_4_1.lab44" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_1.but46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text >> 
    vTcl:DefineAlias "$site_4_1.but46" "button_q_to_a_track" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_1.but47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text << 
    vTcl:DefineAlias "$site_4_1.but47" "button_a_to_q_track" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_1.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text All 
    vTcl:DefineAlias "$site_4_1.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_1.but49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text >>>> 
    vTcl:DefineAlias "$site_4_1.but49" "button_q_to_a_all" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_1.but50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text <<<< 
    vTcl:DefineAlias "$site_4_1.but50" "button_a_to_q_all" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_1.lab43 \
        -in $site_4_1 -x 10 -y 83 -width 64 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but44 \
        -in $site_4_1 -x 5 -y 103 -width 70 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but43 \
        -in $site_4_1 -x 5 -y 138 -width 70 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_1.lab44 \
        -in $site_4_1 -x 10 -y 228 -width 64 -relwidth 0 -height 21 \
        -anchor nw -bordermode ignore 
    place $site_4_1.but46 \
        -in $site_4_1 -x 5 -y 249 -width 70 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_1.but47 \
        -in $site_4_1 -x 5 -y 284 -width 70 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_1.lab48 \
        -in $site_4_1 -x 5 -y 382 -width 64 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_1.but49 \
        -in $site_4_1 -x 5 -y 401 -width 70 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_1.but50 \
        -in $site_4_1 -x 5 -y 436 -width 70 -height 31 -anchor nw \
        -bordermode ignore 
    $top.tPa43 add $top.tPa43.p3 
        
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $top.tPa43.p2 \
        -relief flat -width 505.0 -height 760 
    vTcl:DefineAlias "$top.tPa43.p2" "TPanedwindow1_p2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_2 $top.tPa43.p2
    button $site_4_2.but45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Open Ardour Project} 
    vTcl:DefineAlias "$site_4_2.but45" "button_aopen" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_2.but47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {BACKUP Ardour Project} 
    vTcl:DefineAlias "$site_4_2.but47" "button_abackup" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_2.lab43 \
        -activebackground #f9f9f9 -activeforeground black -anchor n \
        -background #23ccd8 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text Label 
    vTcl:DefineAlias "$site_4_2.lab43" "label_aproject" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure Treeview.Heading -background $vTcl(pr,guicomplement_color)
    ttk::style configure Treeview.Heading -font "$vTcl(actual_gui_font_dft_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_2.scr45 \
        -background $vTcl(actual_gui_bg) -height 661 -highlightcolor black \
        -width 483 
    vTcl:DefineAlias "$site_4_2.scr45" "tree_ctrl_ardour" vTcl:WidgetProc "Toplevel1" 1
        .top42.tPa43.p2.scr45.01 configure -columns {}
        .top42.tPa43.p2.scr45.01 heading #0 -text {Tree}
        .top42.tPa43.p2.scr45.01 heading #0 -anchor center
        .top42.tPa43.p2.scr45.01 column #0 -width 233
        .top42.tPa43.p2.scr45.01 column #0 -minwidth 20
        .top42.tPa43.p2.scr45.01 column #0 -stretch 1
        .top42.tPa43.p2.scr45.01 column #0 -anchor w
    button $site_4_2.but48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Save Ardour Project} 
    vTcl:DefineAlias "$site_4_2.but48" "button_asave" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_2.but45 \
        -in $site_4_2 -x 5 -y 10 -width 191 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_2.but47 \
        -in $site_4_2 -x 195 -y 10 -width 191 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_2.lab43 \
        -in $site_4_2 -x 5 -y 40 -width 475 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.scr45 \
        -in $site_4_2 -x 0 -y 60 -width 483 -relwidth 0 -height 661 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but48 \
        -in $site_4_2 -x 2 -y 728 -width 191 -height 31 -anchor nw \
        -bordermode ignore 
    $top.tPa43 add $top.tPa43.p2 
        
    label $top.lab43 \
        -activebackground #f9f9f9 -activeforeground black -background #23ccd8 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab43" "label_status" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m45
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) \
        -font $vTcl(actual_gui_font_menu_desc) \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tPa43 \
        -in $top -x 10 -y 0 -width 1065 -relwidth 0 -height 760 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 10 -y 760 -width 1060 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

